### ISSUE TITLE
https://connect.sensiolabs.com/faq redirects to "Invalid user help"

### ISSUE THREAD

**Issue by romainneutron** [sensiolabs/connect#55]
https://connect.sensiolabs.com/faq redirects to https://connect.sensiolabs.com/help that displays : 
Unable to find a user or a club named "help"

https://connect.sensiolabs.com/help

**Comment by stof** [comment]
Why closing this ?

**Comment by lyrixx** [comment]
This is "private" stuff, so @romainneutron moved this to the "private" repository that contains connect codebase.
